services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secr3t
    ports:
      - "5432:5432"
  app:
    image: app-store
    depends_on:
      - db
    ports:
      - "8888:8888"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/store
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secr3t
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
